# Generated by Django 3.2.10 on 2022-01-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('Aves', 'Aves'), ('Arroz', 'Arroz'), ('Doces', 'Doces'), ('Bolos', 'Bolos'), ('Caldos', 'Caldos'), ('Carne', 'Carne'), ('Alemã', 'Alemã'), ('Americana', 'Americana'), ('Árabe', 'Árabe'), ('Argentina', 'Argentina'), ('Australiana', 'Australiana'), ('Baiana', 'Baiana'), ('Capixaba', 'Capixaba'), ('Chinesa', 'Chinesa'), ('Colombiana', 'Colombiana'), ('Coreana', 'Coreana'), ('Cubana', 'Cubana'), ('Espanhola', 'Espanhola'), ('Francesa', 'Francesa'), ('Gaúcha', 'Gaúcha'), ('Havaiana', 'Havaiana'), ('Indiana', 'Indiana'), ('Inglesa', 'Inglesa'), ('Italiana', 'Italiana'), ('Japonesa', 'Japonesa'), ('Judaica', 'Judaica'), ('Mexicana', 'Mexicana'), ('Mineira', 'Mineira'), ('Nordestina', 'Nordestina'), ('Pernambucana', 'Pernambucana'), ('Peruana', 'Peruana'), ('Simples', 'Simples'), ('Suíça', 'Suíça'), ('Tailandesa', 'Tailandesa'), ('Vegetariana', 'Vegetariana'), ('Natal', 'Natal'), ('Rápidas', 'Rápidas'), ('Frango', 'Frango'), ('FrutosdoMar', 'FrutosdoMar'), ('Lasanhas', 'Lasanhas'), ('Legumes', 'Legumes'), ('Massas', 'Massas'), ('Molhos', 'Molhos'), ('Peru', 'Peru'), ('Salada', 'Salada'), ('Salmão', 'Salmão'), ('Sanduiches', 'Sanduiches'), ('Light', 'Light'), ('Diet', 'Diet'), ('Portuguesas', 'Portuguesas'), ('-', '-')], default='-', max_length=15)),
                ('imagem', models.ImageField(blank=True, upload_to='')),
                ('descricao', models.TextField(max_length=500)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.restaurante')),
            ],
        ),
    ]
